version: '3.8'

services:
  # Main JWKS Mock API server
  jwks-api:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_ISSUER=http://jwks-api:3000
      - JWT_AUDIENCE=integration-test-api
      - KEY_COUNT=3
      - KEY_IDS=integration-key-1,integration-key-2,integration-key-3
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 3000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - test-network

  # Integration test runner
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    depends_on:
      jwks-api:
        condition: service_healthy
    environment:
      - JWKS_API_URL=http://jwks-api:3000
      - TEST_TIMEOUT=30s
    volumes:
      - ./test/integration:/app/test/integration
      - ./test/integration/results:/app/results
    networks:
      - test-network
    command: ["go", "test", "-v", "./test/integration/..."]

  # Alternative test setup for external testing
  jwks-api-external:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - JWT_ISSUER=http://localhost:3002
      - JWT_AUDIENCE=external-test-api
      - KEY_COUNT=2
      - KEY_IDS=external-key-1,external-key-2
    profiles:
      - external-test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  test-results: